In [1]:
import glob
import numpy as np
from PIL import Image
import pickle
import h5py
filelist = glob.glob('img150/*.jpg')

In [2]:
matx = np.array([np.array(Image.open(fname)) for fname in filelist])

In [4]:
matx.shape

(450, 150, 150, 3)

In [6]:
np.stack(matx)

array([[[[ 46,  36,  24],
         [ 46,  36,  24],
         [ 45,  35,  23],
         ...,
         [ 86, 129,  76],
         [ 88, 131,  78],
         [ 92, 135,  82]],

        [[ 49,  39,  27],
         [ 49,  39,  27],
         [ 47,  37,  25],
         ...,
         [ 88, 131,  78],
         [ 89, 132,  79],
         [ 93, 136,  83]],

        [[ 53,  43,  31],
         [ 52,  42,  30],
         [ 51,  41,  29],
         ...,
         [ 91, 134,  81],
         [ 92, 135,  82],
         [ 95, 138,  85]],

        ...,

        [[ 69,  57,  41],
         [ 69,  57,  41],
         [ 69,  57,  43],
         ...,
         [ 80, 102,  64],
         [ 81,  98,  62],
         [ 83,  94,  60]],

        [[ 64,  55,  38],
         [ 64,  55,  38],
         [ 64,  55,  40],
         ...,
         [ 81, 103,  65],
         [ 82,  99,  63],
         [ 85,  96,  62]],

        [[ 61,  54,  36],
         [ 61,  54,  36],
         [ 61,  54,  38],
         ...,
         [ 81, 103,  65],
        

In [5]:
print(matx)

[[[[ 46  36  24]
   [ 46  36  24]
   [ 45  35  23]
   ...
   [ 86 129  76]
   [ 88 131  78]
   [ 92 135  82]]

  [[ 49  39  27]
   [ 49  39  27]
   [ 47  37  25]
   ...
   [ 88 131  78]
   [ 89 132  79]
   [ 93 136  83]]

  [[ 53  43  31]
   [ 52  42  30]
   [ 51  41  29]
   ...
   [ 91 134  81]
   [ 92 135  82]
   [ 95 138  85]]

  ...

  [[ 69  57  41]
   [ 69  57  41]
   [ 69  57  43]
   ...
   [ 80 102  64]
   [ 81  98  62]
   [ 83  94  60]]

  [[ 64  55  38]
   [ 64  55  38]
   [ 64  55  40]
   ...
   [ 81 103  65]
   [ 82  99  63]
   [ 85  96  62]]

  [[ 61  54  36]
   [ 61  54  36]
   [ 61  54  38]
   ...
   [ 81 103  65]
   [ 82  99  63]
   [ 85  96  62]]]


 [[[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255